# Generated by Django 5.0.6 on 2024-07-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
